service: cluster-headache-tracker
image: crmne/cluster-headache-tracker

servers:
  web:
    hosts:
      - 188.245.107.117
    labels:
      traefik.http.routers.blog.entrypoints: websecure
      traefik.http.routers.blog.rule: Host(`clusterheadachetracker.com`)
      traefik.http.routers.blog.tls.certresolver: letsencrypt
    options:
      add-host: host.docker.internal:host-gateway

registry:
  username: crmne
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DATABASE_URL: postgres://cluster_headache_tracker:cluster_headache_tracker@host.docker.internal/cluster_headache_tracker_production
  secret:
    - RAILS_MASTER_KEY

builder:
  multiarch: false

accessories:
  db:
    image: postgres:latest
    host: 188.245.107.117
    port: 172.17.0.1:5432:5432
    env:
      clear:
        POSTGRES_USER: cluster_headache_tracker
        POSTGRES_PASSWORD: cluster_headache_tracker
        POSTGRES_DB: cluster_headache_tracker_production
      secret:
        - CLUSTER_HEADACHE_TRACKER_DATABASE_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json" # To save the configuration file.
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure # We want to force https
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "carmine@paolino.me"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json" # Must match the path in `volume`
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web # Must match the role in `servers`
